[package]
name = "submap"
version = "0.1.1"
edition = "2021"
authors = ["Sergei S. <div@altertech.com>"]
license = "Apache-2.0"
repository = "https://github.com/alttch/submap"
description = "B-Tree map for pub/sub services"
readme = "README.md"
keywords = ["pubsub", "subscription", "b-tree", "btree", "map"]

[dependencies]
